# Site settings
title: 小崔的博客
tagline: 
email: cjw624923@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Hi, I'm a Web Developer, 热爱ROR开发, HTML CSS Javascript学习, 目标成为一名Full Stack Developer.
baseurl: "" # the subpath of your siimte, e.g. /blog/
url: "http://xiaocuixt.github.io" # the base hostname & protocol for your site
logourl: /assets/images/logo.png # Site logo
author: "XiaoCui"
author_thumbnail: "/assets/images/avatar.jpg" # Author avatar
# Theme customization - please change from the defaults!
theme:
  # Color for sidebar bar, links, etc
  highlight_color: "#205081" #205081" # "#272935"
  # Social media links, leave blank to ignore
  social: 
    github: xiaocuixt
    twitter: xiaocuixt
    facebook: xiaocuixt
    gplus: +xiaocuixt
    # dribble: gayanvirajith
    pinterest: xiaocuixt

  # Enable share buttons on post footer
  show_share_buttons: true

  # Show author picure, name and social links on post footer
  show_author_info: true

  # Disqus comments manager - shortname
  disqus_shortname: xiaocuixt

  # Google Analytics/Webmaster key, leave blank to ignore
  google_analytics_key: 
  google_webmaster_key: 

# Build settings
markdown: kramdown

# Permalinks
permalink:        pretty

# Pagination config
paginate: 5

# Files/Folders to be excluded from generated _site folder
exclude: 
  - CNAME
  - Gemfile
  - Rakefile
  - README.md
  - .gitignore
  - .sass-cache
  - Gemfile.lock

# Sass conversion configs
sass:
  sass_dir: assets/css/_sass
  style: :compressed
